[toolchain]
package_manager = "pnpm"
anchor_version = "0.30.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_marketplace = "2zfumnLEef5h94RVLi3CtoPPBWiSySFvePKg5pP64WYh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
